#!/usr/bin/env bash
# freepool-install.sh — one-shot local install for the free-claude-code proxy
# (T19). Clones the repo, creates a venv, installs deps, and pins the checked-
# out commit hash into config/freepool-arm.yaml for reproducibility. Never
# writes secrets into git — provider API keys stay in the proxy's own .env
# under FREEPOOL_INSTALL_DIR, which is outside this plugin repo.
#
# Idempotent: re-running updates the pin file to the currently checked-out
# commit but does not force-reset an existing checkout (so a local operator
# can pin to a specific tested commit without this script clobbering it).
set -euo pipefail

readonly FREEPOOL_REPO_URL="${FREEPOOL_REPO_URL:-https://github.com/Alishahryar1/free-claude-code.git}"
readonly FREEPOOL_INSTALL_DIR="${FREEPOOL_INSTALL_DIR:-${HOME}/tools/free-claude-code}"
readonly PIN_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/config/freepool-arm.yaml"
# T19 fix-round-2 (B-H1): the commit actually reviewed/tested, resolved once via
# `git ls-remote https://github.com/Alishahryar1/free-claude-code.git HEAD` on
# 2026-08-26 and hardcoded here as the default -- the prior default (empty) meant
# "install whatever the upstream default branch has drifted to and merely warn",
# which is the opposite of what the pin file's own generated comment claimed
# ("what was actually reviewed/tested"). A caller can still override PINNED_COMMIT
# to move to a newly reviewed commit; FREEPOOL_ALLOW_UNPINNED=1 restores the old
# "install unpinned HEAD" behaviour explicitly, for anyone who really wants it.
# NOTE: `-` not `:-` -- a caller that explicitly sets PINNED_COMMIT="" (to ask
# for an unpinned install) must stay empty and hit the refusal guard below;
# `:-` would silently paper over that explicit empty back to the hardcoded
# default, making the guard unreachable.
readonly PINNED_COMMIT="${PINNED_COMMIT-6b3f16f41d4b06ab1320c0d0e71007392a676348}"
readonly FREEPOOL_ALLOW_UNPINNED="${FREEPOOL_ALLOW_UNPINNED:-0}"

log() { echo "[freepool-install] $*" >&2; }

if [[ -z "${PINNED_COMMIT}" && "${FREEPOOL_ALLOW_UNPINNED}" != "1" ]]; then
  log "refusing to install: PINNED_COMMIT is empty and FREEPOOL_ALLOW_UNPINNED != 1 --" \
      "set PINNED_COMMIT=<sha> to a reviewed commit, or FREEPOOL_ALLOW_UNPINNED=1 to" \
      "explicitly accept an unpinned install"
  exit 1
fi

if [[ ! -d "${FREEPOOL_INSTALL_DIR}/.git" ]]; then
  log "cloning ${FREEPOOL_REPO_URL} -> ${FREEPOOL_INSTALL_DIR}"
  git clone "${FREEPOOL_REPO_URL}" "${FREEPOOL_INSTALL_DIR}"
else
  log "checkout already present at ${FREEPOOL_INSTALL_DIR} — not re-cloning (this script does not force-reset)"
fi

if [[ -n "${PINNED_COMMIT}" ]]; then
  log "checking out pinned commit ${PINNED_COMMIT}"
  git -C "${FREEPOOL_INSTALL_DIR}" fetch --quiet origin "${PINNED_COMMIT}" 2>/dev/null || true
  git -C "${FREEPOOL_INSTALL_DIR}" checkout --quiet "${PINNED_COMMIT}"
else
  log "PINNED_COMMIT not set (FREEPOOL_ALLOW_UNPINNED=1) -- installing whatever commit is" \
      "currently checked out (untested provenance)"
fi

if [[ ! -d "${FREEPOOL_INSTALL_DIR}/.venv" ]]; then
  log "creating venv"
  python3 -m venv "${FREEPOOL_INSTALL_DIR}/.venv"
fi

if [[ -f "${FREEPOOL_INSTALL_DIR}/requirements.txt" ]]; then
  log "installing requirements.txt"
  "${FREEPOOL_INSTALL_DIR}/.venv/bin/pip" install -q -r "${FREEPOOL_INSTALL_DIR}/requirements.txt"
else
  log "no requirements.txt found yet (repo not cloned in this environment) — skipping pip install"
fi

commit_hash="$(git -C "${FREEPOOL_INSTALL_DIR}" rev-parse HEAD 2>/dev/null || echo UNRESOLVED)"
cat > "${PIN_FILE}" <<EOF
# freepool-arm.yaml — generated by freepool-install.sh. Pinned commit is what
# was actually checked out at ${FREEPOOL_INSTALL_DIR} at install time; a
# mismatch between this and a live \`git -C \$FREEPOOL_INSTALL_DIR rev-parse
# HEAD\` means the local checkout drifted from what was reviewed/tested.
repo_url: ${FREEPOOL_REPO_URL}
pinned_commit: ${commit_hash}
install_dir: ${FREEPOOL_INSTALL_DIR}

# Provider API keys the proxy itself needs — NEVER set here, NEVER in git.
# Configure them in \${FREEPOOL_INSTALL_DIR}/.env per the cloned repo's own
# README/.env.example (exact names are UNVERIFIED until the repo is cloned in
# a network-enabled environment — see freepool-proxy.sh's ENTRYPOINT-UNVERIFIED
# note for the same caveat on the run command). Until that file has real
# values, leadv2-freepool-gate.sh's liveness probe fails closed (arm_down) and
# the router skips this arm by fact — no code change needed when keys land,
# only the .env file and a \`freepool-proxy.sh start\`.
EOF
log "pinned commit ${commit_hash} -> ${PIN_FILE}"
log "next: put provider keys in ${FREEPOOL_INSTALL_DIR}/.env, then freepool-proxy.sh start"
