#!/usr/bin/env bash
# freepool-install.sh — one-shot local install for the free-claude-code proxy
# (T19). Clones the repo, creates a venv, installs deps, and pins the checked-
# out commit hash into config/freepool-arm.yaml for reproducibility. Never
# writes secrets into git — provider API keys stay in the proxy's own .env
# under FREEPOOL_INSTALL_DIR, which is outside this plugin repo.
#
# Idempotent: re-running updates the pin file to the currently checked-out
# commit but does not force-reset an existing checkout (so a local operator
# can pin to a specific tested commit without this script clobbering it).
set -euo pipefail

readonly FREEPOOL_REPO_URL="${FREEPOOL_REPO_URL:-https://github.com/Alishahryar1/free-claude-code.git}"
readonly FREEPOOL_INSTALL_DIR="${FREEPOOL_INSTALL_DIR:-${HOME}/tools/free-claude-code}"
readonly PIN_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/config/freepool-arm.yaml"

log() { echo "[freepool-install] $*" >&2; }

if [[ ! -d "${FREEPOOL_INSTALL_DIR}/.git" ]]; then
  log "cloning ${FREEPOOL_REPO_URL} -> ${FREEPOOL_INSTALL_DIR}"
  git clone "${FREEPOOL_REPO_URL}" "${FREEPOOL_INSTALL_DIR}"
else
  log "checkout already present at ${FREEPOOL_INSTALL_DIR} — not re-cloning (this script does not force-reset)"
fi

if [[ ! -d "${FREEPOOL_INSTALL_DIR}/.venv" ]]; then
  log "creating venv"
  python3 -m venv "${FREEPOOL_INSTALL_DIR}/.venv"
fi

if [[ -f "${FREEPOOL_INSTALL_DIR}/requirements.txt" ]]; then
  log "installing requirements.txt"
  "${FREEPOOL_INSTALL_DIR}/.venv/bin/pip" install -q -r "${FREEPOOL_INSTALL_DIR}/requirements.txt"
else
  log "no requirements.txt found yet (repo not cloned in this environment) — skipping pip install"
fi

commit_hash="$(git -C "${FREEPOOL_INSTALL_DIR}" rev-parse HEAD 2>/dev/null || echo UNRESOLVED)"
cat > "${PIN_FILE}" <<EOF
# freepool-arm.yaml — generated by freepool-install.sh. Pinned commit is what
# was actually checked out at ${FREEPOOL_INSTALL_DIR} at install time; a
# mismatch between this and a live \`git -C \$FREEPOOL_INSTALL_DIR rev-parse
# HEAD\` means the local checkout drifted from what was reviewed/tested.
repo_url: ${FREEPOOL_REPO_URL}
pinned_commit: ${commit_hash}
install_dir: ${FREEPOOL_INSTALL_DIR}

# Provider API keys the proxy itself needs — NEVER set here, NEVER in git.
# Configure them in \${FREEPOOL_INSTALL_DIR}/.env per the cloned repo's own
# README/.env.example (exact names are UNVERIFIED until the repo is cloned in
# a network-enabled environment — see freepool-proxy.sh's ENTRYPOINT-UNVERIFIED
# note for the same caveat on the run command). Until that file has real
# values, leadv2-freepool-gate.sh's liveness probe fails closed (arm_down) and
# the router skips this arm by fact — no code change needed when keys land,
# only the .env file and a \`freepool-proxy.sh start\`.
EOF
log "pinned commit ${commit_hash} -> ${PIN_FILE}"
log "next: put provider keys in ${FREEPOOL_INSTALL_DIR}/.env, then freepool-proxy.sh start"
