#!/usr/bin/env bash
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/leadv2-temp.sh"
# leadv2_rate_limit_summary (PLUGIN-COST-METRIC-RATELIMIT-01) — best-effort,
# never fatal if helpers are unavailable (e.g. standalone invocation).
_LV2_STATUS_HELPERS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/leadv2-helpers.sh"
[[ -f "$_LV2_STATUS_HELPERS" ]] && { source "$_LV2_STATUS_HELPERS" 2>/dev/null || true; }
unset _LV2_STATUS_HELPERS
# leadv2-status.sh — Compact founder-facing status summary for /leadv2 daemon.
#
# Usage: leadv2-status.sh [--json]
#
# Reads:
#   docs/LEAD_V2_STATUS.md     — formatted live dashboard (regenerated by daemon)
#   docs/leadv2-decisions/*.yaml  — pending decisions
#   /tmp/leadv2-daemon.state   — raw daemon state (if running)
#
# Exit codes:
#   0 = all good
#   1 = daemon paused
#   2 = pending decisions > 0
#   3 = both paused AND pending decisions

PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"
STATUS_MD="${PROJECT_ROOT}/docs/LEAD_V2_STATUS.md"
DECISIONS_DIR="${PROJECT_ROOT}/docs/leadv2-decisions"
DAEMON_STATE="/tmp/leadv2-daemon.state"
# DOD-GATE-CHARGES-LANES-FOR-HARNESS-WRITES-01: prefer the shared
# control-plane copy; see leadv2-active-registry.sh's writer comment.
if [[ -z "${LEADV2_LEAD_STATE_PATH:-}" ]]; then
  _lv2_sp="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/leadv2-state-path.sh"
  [[ -x "$_lv2_sp" ]] && LEADV2_LEAD_STATE_PATH="$(PROJECT_ROOT="$PROJECT_ROOT" "$_lv2_sp" --no-link LEAD_V2_STATE.md 2>/dev/null || true)"
  unset _lv2_sp
fi
LEAD_STATE="${LEADV2_LEAD_STATE_PATH:-${PROJECT_ROOT}/docs/LEAD_V2_STATE.md}"
QUEUE_DIR="${PROJECT_ROOT}/docs/agents/product-owner/queue"

CAUSAL_LOG="${PROJECT_ROOT}/docs/leadv2-causal-log.yaml"

JSON_MODE=0
CAUSAL_LOG_MODE=0
COST_MODE=0
CACHE_MODE=0
DAILY_BUDGET_SCRIPT="${PROJECT_ROOT}/.claude/scripts/leadv2-daily-budget.sh"
QUOTA_SCRIPT="${PROJECT_ROOT}/.claude/scripts/leadv2-quota-status.sh"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --json)       JSON_MODE=1;       shift ;;
    --causal-log) CAUSAL_LOG_MODE=1; shift ;;
    --cost)       COST_MODE=1;       shift ;;
    --cache)      CACHE_MODE=1;      shift ;;
    -h|--help)
      echo "Usage: leadv2-status.sh [--json] [--causal-log] [--cost] [--cache]" >&2
      exit 0
      ;;
    *) echo "[leadv2-status] unknown arg: $1" >&2; exit 1 ;;
  esac
done

# ── Helpers ────────────────────────────────────────────────────────────────────

RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'

# Count pending decisions
count_pending() {
  local count=0
  if [[ -d "$DECISIONS_DIR" ]]; then
    while IFS= read -r f; do
      [[ -z "$f" ]] && continue
      if grep -q 'status: pending' "$f" 2>/dev/null; then
        count=$((count + 1))
      fi
    done < <(find "$DECISIONS_DIR" -maxdepth 1 -name '*.yaml' ! -name '_*' 2>/dev/null)
  fi
  echo "$count"
}

# ── Causal log mode ───────────────────────────────────────────────────────────
if [[ "$CAUSAL_LOG_MODE" -eq 1 ]]; then
  if [[ ! -f "$CAUSAL_LOG" ]]; then
    echo "(causal log is empty)"
    exit 0
  fi
  python3 - "$CAUSAL_LOG" <<'PY'
import sys, yaml
with open(sys.argv[1]) as fh:
    entries = yaml.safe_load(fh) or []
if not entries:
    print("(causal log is empty)")
    sys.exit(0)
print("=== Last 10 causal links ===")
for entry in list(reversed(entries))[:10]:
    cause   = entry.get("cause_task") or "(unknown)"
    score   = entry.get("causality_score", 0)
    effect  = entry.get("effect_task", "")
    ts      = str(entry.get("timestamp", ""))[:10]
    lesson  = entry.get("mechanism", "")
    unknown = entry.get("cause_unknown", False)
    flag    = " [CAUSE UNKNOWN]" if unknown else ""
    print(f"  {ts}  {effect} <- {cause}  score={score:.2f}{flag}")
    if lesson:
        print(f"    {lesson}")
PY
  exit 0
fi

# ── Read prior-art summary for current task from LEAD_V2_STATE.md + prior-art.yaml
get_prior_art_summary() {
  [[ -f "$LEAD_STATE" ]] || { echo ""; return; }
  local task_id
  task_id=$(awk '/^task:/ {print $2; exit}' "$LEAD_STATE")
  [[ -z "$task_id" ]] && { echo ""; return; }

  local prior_art_file="${PROJECT_ROOT}/docs/handoff/${task_id}/prior-art.yaml"
  if [[ ! -f "$prior_art_file" ]]; then
    echo ""
    return
  fi

  # Parse first entry: task_id, similarity, outcome
  python3 - "$prior_art_file" <<'PY'
import sys, yaml
with open(sys.argv[1]) as fh:
    data = yaml.safe_load(fh)
if not data or not isinstance(data, list) or len(data) == 0:
    print("")
    sys.exit(0)
top = data[0]
tid = top.get("task_id", "")
sim = top.get("similarity", 0)
out = top.get("outcome", "")
if tid and sim:
    print(f"{tid} (sim {sim:.2f}, outcome: {out})")
else:
    print("")
PY
}

# Get premortem + llm-judge verdicts for current task
get_gate_verdicts() {
  [[ -f "$LEAD_STATE" ]] || { printf ''; return; }
  local task_id
  task_id=$(awk '/^task:/ {print $2; exit}' "$LEAD_STATE")
  [[ -z "$task_id" ]] && { printf ''; return; }

  local handoff_dir="${PROJECT_ROOT}/docs/handoff/${task_id}"
  python3 - "$handoff_dir" <<'PY'
import sys, os, yaml

handoff = sys.argv[1]
parts = []

for phase in ("build", "deploy"):
    pf = os.path.join(handoff, f"premortem-{phase}.yaml")
    if os.path.isfile(pf):
        try:
            d = yaml.safe_load(open(pf)) or {}
            pre = d.get("premortem", d)
            verdict = pre.get("verdict", "?")
            prob = pre.get("predicted_outcome_prob", {}).get("success", "?")
            parts.append(f"premortem-{phase}={verdict}({prob:.2f})" if isinstance(prob, float) else f"premortem-{phase}={verdict}")
        except Exception:
            pass

jf = os.path.join(handoff, "llm-judge.yaml")
if os.path.isfile(jf):
    try:
        d = yaml.safe_load(open(jf)) or {}
        lj = d.get("llm_judge", d)
        verdict = lj.get("verdict", "?")
        risk = lj.get("overall_risk", "?")
        skipped = lj.get("skipped", False)
        if skipped:
            parts.append(f"llm-judge=skipped")
        else:
            parts.append(f"llm-judge={verdict}(risk={risk})")
    except Exception:
        pass

print(" | ".join(parts) if parts else "")
PY
}

# Get top N pending decision summaries: "id|question"
top_pending() {
  local max="${1:-3}"
  local shown=0
  if [[ -d "$DECISIONS_DIR" ]]; then
    while IFS= read -r f; do
      [[ -z "$f" ]] && continue
      if grep -q 'status: pending' "$f" 2>/dev/null; then
        local id question
        id=$(grep -m1 '^id:' "$f" | sed "s/id: //;s/['\"]//g" | xargs)
        question=$(grep -m1 '^question:' "$f" | sed "s/question: //;s/['\"]//g" | xargs)
        printf '%s|%s\n' "$id" "$question"
        shown=$((shown + 1))
        [[ "$shown" -ge "$max" ]] && break
      fi
    done < <(find "$DECISIONS_DIR" -maxdepth 1 -name '*.yaml' ! -name '_*' 2>/dev/null | sort)
  fi
}

# Read a field from daemon state file
get_state_field() {
  local field="$1"
  [[ -f "$DAEMON_STATE" ]] || { echo ""; return; }
  awk -v f="$field" '$1 == f":" {$1=""; sub(/^ /,""); print; exit}' "$DAEMON_STATE"
}

# ── Collect data ───────────────────────────────────────────────────────────────

PAUSED=$(get_state_field paused)
FAILS=$(get_state_field consecutive_failures)
LAST_TASK=$(get_state_field last_task_id)
LAST_OUTCOME=$(get_state_field last_outcome)
LAST_FAILURE=$(get_state_field last_failure)
UPDATED_AT=$(get_state_field updated_at)
[[ -z "$FAILS" ]] && FAILS=0

PENDING_COUNT=$(count_pending)

# Determine exit code
EXIT_CODE=0
IS_PAUSED=0
HAS_DECISIONS=0
[[ "$PAUSED" == "true" ]] && IS_PAUSED=1
[[ "$PENDING_COUNT" -gt 0 ]] && HAS_DECISIONS=1

if [[ "$IS_PAUSED" -eq 1 && "$HAS_DECISIONS" -eq 1 ]]; then
  EXIT_CODE=3
elif [[ "$IS_PAUSED" -eq 1 ]]; then
  EXIT_CODE=1
elif [[ "$HAS_DECISIONS" -eq 1 ]]; then
  EXIT_CODE=2
fi

# ── JSON output ────────────────────────────────────────────────────────────────

if [[ "$JSON_MODE" -eq 1 ]]; then
  python3 - "$PAUSED" "$FAILS" "$LAST_TASK" "$LAST_OUTCOME" "$LAST_FAILURE" "$UPDATED_AT" "$PENDING_COUNT" "$EXIT_CODE" "$DECISIONS_DIR" "$QUEUE_DIR" <<'PY'
import sys, json, os, glob, yaml

paused        = sys.argv[1] == "true"
fails         = int(sys.argv[2]) if sys.argv[2] else 0
last_task     = sys.argv[3]
last_outcome  = sys.argv[4]
last_failure  = sys.argv[5]
updated_at    = sys.argv[6]
pending_count = int(sys.argv[7])
exit_code     = int(sys.argv[8])
decisions_dir = sys.argv[9]
queue_dir     = sys.argv[10]

pending_decisions = []
for f in sorted(glob.glob(os.path.join(decisions_dir, "*.yaml"))):
    if os.path.basename(f).startswith("_"):
        continue
    try:
        with open(f) as fh:
            d = yaml.safe_load(fh) or {}
        if d.get("status") == "pending":
            pending_decisions.append({
                "id": d.get("id", ""),
                "task_id": d.get("task_id", ""),
                "question": d.get("question", ""),
                "trigger": d.get("trigger", ""),
            })
    except Exception:
        pass

# Lane counts
lanes_summary: dict[str, dict[str, int]] = {}
LANES = ["action", "intelligence", "recovery", "human-needed"]
for lane in LANES:
    lf = os.path.join(queue_dir, f"{lane}.yaml")
    counts: dict[str, int] = {}
    if os.path.exists(lf):
        try:
            items = yaml.safe_load(open(lf)) or []
            for it in items:
                s = str(it.get("status", "unknown"))
                counts[s] = counts.get(s, 0) + 1
        except Exception:
            pass
    lanes_summary[lane] = counts

# Gate verdicts (premortem + llm-judge) for current task
gate_verdicts: dict[str, object] = {}
if last_task:
    handoff = os.path.join(os.path.dirname(decisions_dir), "handoff", last_task)
    for phase_name in ("build", "deploy"):
        pf = os.path.join(handoff, f"premortem-{phase_name}.yaml")
        if os.path.isfile(pf):
            try:
                with open(pf) as fh:
                    d = yaml.safe_load(fh) or {}
                pre = d.get("premortem", d)
                gate_verdicts[f"premortem_{phase_name}"] = {
                    "verdict": pre.get("verdict", "?"),
                    "success_prob": pre.get("predicted_outcome_prob", {}).get("success"),
                }
            except Exception:
                pass
    jf = os.path.join(handoff, "llm-judge.yaml")
    if os.path.isfile(jf):
        try:
            with open(jf) as fh:
                d = yaml.safe_load(fh) or {}
            lj = d.get("llm_judge", d)
            gate_verdicts["llm_judge"] = {
                "verdict": lj.get("verdict"),
                "overall_risk": lj.get("overall_risk"),
                "skipped": lj.get("skipped", False),
            }
        except Exception:
            pass

print(json.dumps({
    "paused": paused,
    "consecutive_failures": fails,
    "last_task": last_task,
    "last_outcome": last_outcome,
    "last_failure": last_failure,
    "updated_at": updated_at,
    "pending_decisions_count": pending_count,
    "pending_decisions": pending_decisions[:3],
    "exit_code": exit_code,
    "lanes": lanes_summary,
    "gate_verdicts": gate_verdicts,
}, indent=2))
PY
  exit "$EXIT_CODE"
fi

# ── Cost mode (--cost / --quota): 5h + weekly token quota ──────────────────────
if [[ "$COST_MODE" -eq 1 ]]; then
  printf '%b\n' "${CYAN}=== Quota (tokens, subscription) ===${NC}"
  if [[ -x "$QUOTA_SCRIPT" ]]; then
    bash "$QUOTA_SCRIPT" --report 2>/dev/null || true
  elif [[ -f "$DAILY_BUDGET_SCRIPT" ]]; then
    bash "$DAILY_BUDGET_SCRIPT" --report 2>/dev/null || true
  fi
  printf '\n'
  exit 0
fi

# ── Cache mode (--cache): avg cache-hit rate last 24h ─────────────────────────
if [[ "${CACHE_MODE:-0}" -eq 1 ]]; then
  printf '%b\n' "${CYAN}=== Cache-hit rate (last 24h) ===${NC}"
  _CACHE_PY=$(lv2_mktemp_file "leadv2-cache-stat" "py")
  # shellcheck disable=SC2064
  trap "rm -f '$_CACHE_PY'" RETURN
  python3 -c "
print(open('/dev/stdin').read())
" /dev/stdin > "$_CACHE_PY" 2>/dev/null <<'CACHESCRIPTEOF'
import sys, os, yaml
from datetime import datetime, timezone, timedelta

handoff_root = sys.argv[1]
cutoff = datetime.now(timezone.utc) - timedelta(hours=24)

total_input = 0
total_cache_read = 0
tasks_scanned = 0
entries_found = 0

RED   = "\033[0;31m"
YELLOW= "\033[1;33m"
NC    = "\033[0m"

if not os.path.isdir(handoff_root):
    print("(no handoff dir found)")
    sys.exit(0)

for task_dir in sorted(os.listdir(handoff_root)):
    costs_file = os.path.join(handoff_root, task_dir, "costs.yaml")
    if not os.path.isfile(costs_file):
        continue
    tasks_scanned += 1
    try:
        entries = yaml.safe_load(open(costs_file)) or []
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            ts_str = entry.get("timestamp", "")
            try:
                ts = datetime.fromisoformat(ts_str.rstrip("Z")).replace(tzinfo=timezone.utc) if ts_str else None
            except Exception:
                ts = None
            if ts and ts < cutoff:
                continue
            it = int(entry.get("input_tokens", 0))
            chr_val = entry.get("cache_hit_rate")
            if chr_val not in (None, "null", "") and it > 0:
                entries_found += 1
                total_input += it
                if isinstance(chr_val, float):
                    total_cache_read += int(chr_val * it)
    except Exception:
        pass

if total_input == 0:
    print("(no token data in last 24h)")
    sys.exit(0)

rate = total_cache_read / total_input if total_input > 0 else 0
rate_pct = rate * 100
if rate_pct < 30:
    color = RED
    flag  = "  [RED: cache broken — check TTL / prefix stability]"
elif rate_pct < 50:
    color = YELLOW
    flag  = "  [YELLOW: cache below 50%]"
else:
    color = ""
    flag  = ""

print(f"{color}Cache-hit rate (24h): {rate_pct:.1f}%  cache_read={total_cache_read:,} / input={total_input:,}{NC}{flag}")
print(f"Tasks scanned: {tasks_scanned}  |  Entries with cache data: {entries_found}")
CACHESCRIPTEOF
  python3 "$_CACHE_PY" "${PROJECT_ROOT}/docs/handoff" 2>/dev/null || true
  rm -f "$_CACHE_PY"
  printf '\n'
  exit 0
fi

# ── Human-friendly output ──────────────────────────────────────────────────────

# Compact cost line — always shown (top of output).
# PLUGIN-COST-METRIC-RATELIMIT-01: no dollar figures — the only cost metrics
# reported are the task's %-of-budget-cap (a ratio, not a currency amount) and
# the fleet-wide 5h/weekly rate-limit window usage (single source:
# leadv2-quota-status.sh --json, same one leadv2-helpers.sh's
# leadv2_rate_limit_summary wraps).
_print_cost_compact() {
  local task_id
  task_id=$(awk '/^task:/ {print $2; exit}' "$LEAD_STATE" 2>/dev/null || true)

  # Per-task burn, expressed as % of its class cap (never as $).
  local task_pct=""
  if [[ -n "$task_id" ]]; then
    local task_class
    task_class=$(awk '/^classification:/ {print $2; exit}' "$LEAD_STATE" 2>/dev/null || true)
    local costs_file="${PROJECT_ROOT}/docs/handoff/${task_id}/costs.yaml"
    local task_cap
    case "${task_class:-Standard}" in
      Light)    task_cap="0.50"  ;;
      Standard) task_cap="2.00"  ;;
      Heavy)    task_cap="8.00"  ;;
      Strategic) task_cap="20.00" ;;
      *)        task_cap="2.00"  ;;
    esac
    if [[ -f "$costs_file" ]]; then
      task_pct=$(python3 -c "
import yaml, sys
entries = yaml.safe_load(open(sys.argv[1])) or []
total = sum(float(e.get('cost_usd',0)) for e in entries if isinstance(e, dict) and 'cost_usd' in e)
cap = float(sys.argv[2])
print(f'{total/cap*100:.0f}%' if cap > 0 else '?')
" "$costs_file" "$task_cap" 2>/dev/null || true)
    fi
  fi

  # Fleet-wide rate-limit window usage — one source, reused everywhere.
  local rl_line
  if [[ -x "$QUOTA_SCRIPT" ]]; then
    rl_line=$(LEADV2_QUOTA_STATUS_SCRIPT="$QUOTA_SCRIPT" leadv2_rate_limit_summary 2>/dev/null || true)
  fi
  [[ -z "${rl_line:-}" ]] && rl_line="rate-limit: unavailable"

  local task_part=""
  [[ -n "$task_pct" ]] && task_part="task ${task_pct} of budget cap"

  local cost_line=""
  [[ -n "$task_part" ]] && cost_line="${task_part} | ${rl_line}"
  [[ -z "$cost_line" ]] && cost_line="${rl_line}"

  # Color: task >=85% = red, >=60% = yellow.
  local color="${NC}"
  local pct_num
  pct_num=$(printf '%s' "${task_pct/\%/}" | grep -Eo '[0-9]+' | head -1 || true)
  if [[ -n "$pct_num" ]]; then
    if [[ "$pct_num" -ge 85 ]]; then
      color="${RED}"
    elif [[ "$pct_num" -ge 60 ]]; then
      color="${YELLOW}"
    fi
  fi
  printf '%b\n' "${color}Cost: ${cost_line}${NC}"
}

# Print the status file if it exists
if [[ -f "$STATUS_MD" ]]; then
  printf '\n'
  cat "$STATUS_MD"
  printf '\n'
fi

_print_cost_compact
printf '\n'

# Overlay with live daemon state
if [[ -f "$DAEMON_STATE" ]]; then
  printf '%b\n' "${CYAN}=== Live daemon state ===${NC}"
  printf -- '  paused:               %s\n' "${PAUSED:-—}"
  printf -- '  consecutive_failures: %s\n' "${FAILS}"
  printf -- '  last_task:            %s\n' "${LAST_TASK:-—}"
  printf -- '  last_outcome:         %s\n' "${LAST_OUTCOME:-—}"
  printf -- '  last_failure:         %s\n' "${LAST_FAILURE:-—}"
  printf -- '  updated_at:           %s\n' "${UPDATED_AT:-—}"
  printf '\n'
fi

# ── VPS smoke status for current task ─────────────────────────────────────────
get_smoke_status() {
  [[ -f "$LEAD_STATE" ]] || { printf ''; return; }
  local task_id
  task_id=$(awk '/^task:/ {print $2; exit}' "$LEAD_STATE")
  [[ -z "$task_id" ]] && { printf ''; return; }

  local handoff_dir="${PROJECT_ROOT}/docs/handoff/${task_id}"
  python3 - "$handoff_dir" <<'PY'
import sys, os, yaml, datetime

handoff = sys.argv[1]
parts = []

import glob as _glob
smoke_files = sorted(_glob.glob(os.path.join(handoff, "vps-smoke-*.yaml")))
for report_file in smoke_files:
    target = os.path.basename(report_file)[len("vps-smoke-"):-len(".yaml")]
    if not os.path.isfile(report_file):
        continue
    try:
        d = yaml.safe_load(open(report_file)) or {}
        sr = d.get("smoke_result", {})
        verdict = sr.get("verdict", "?")
        detail  = sr.get("failure_detail") or ""
        ts_str  = sr.get("timestamp", "")
        # Compute age
        age_str = ""
        if ts_str:
            try:
                ts = datetime.datetime.strptime(ts_str, "%Y-%m-%dT%H:%M:%SZ")
                age_s = int((datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None) - ts).total_seconds())
                age_str = f" ({age_s//60}m ago)"
            except Exception:
                pass
        if verdict == "pass":
            parts.append(f"smoke/{target}: PASS{age_str}")
        else:
            detail_short = (": " + detail[:60]) if detail and detail != "null" else ""
            parts.append(f"smoke/{target}: FAIL{detail_short}{age_str}")
    except Exception:
        pass

if parts:
    print(" | ".join(parts))
PY
}

SMOKE_STATUS=$(get_smoke_status)
if [[ -n "$SMOKE_STATUS" ]]; then
  printf '%b\n' "${CYAN}VPS Smoke:${NC} ${SMOKE_STATUS}"
  printf '\n'
fi

# Gate verdicts for current task (premortem + llm-judge)
GATE_VERDICTS=$(get_gate_verdicts)
if [[ -n "$GATE_VERDICTS" ]]; then
  printf '%b\n' "${CYAN}Gate verdicts:${NC} ${GATE_VERDICTS}"
  printf '\n'
fi

# Prior-art summary for current task
PRIOR_ART_SUMMARY=$(get_prior_art_summary)
if [[ -n "$PRIOR_ART_SUMMARY" ]]; then
  printf '%b\n' "${CYAN}Prior art:${NC} ${PRIOR_ART_SUMMARY}"
  printf '\n'
fi

# Causal context for current task if it's a RECOVERY-
get_causal_context() {
  [[ -f "$LEAD_STATE" ]] || { echo ""; return; }
  local task_id
  task_id=$(awk '/^task:/ {print $2; exit}' "$LEAD_STATE")
  [[ -z "$task_id" ]] && { echo ""; return; }
  # Only show for RECOVERY- tasks
  [[ "$task_id" != RECOVERY-* ]] && { echo ""; return; }

  [[ -f "$CAUSAL_LOG" ]] || { echo ""; return; }

  python3 - "$CAUSAL_LOG" "$task_id" <<'PY'
import sys, yaml
with open(sys.argv[1]) as fh:
    entries = yaml.safe_load(fh) or []
task_id = sys.argv[2]
for entry in reversed(entries):
    if entry.get("effect_task") == task_id:
        cause   = entry.get("cause_task") or None
        score   = entry.get("causality_score", 0)
        lesson  = entry.get("mechanism", "")
        unknown = entry.get("cause_unknown", False)
        if unknown or not cause:
            print("Caused by: unknown (causal lookup inconclusive)")
        else:
            print(f"Caused by: {cause} (sim {score:.2f}, lesson: {lesson})")
        sys.exit(0)
PY
}

CAUSAL_CTX=$(get_causal_context)
if [[ -n "$CAUSAL_CTX" ]]; then
  printf '%b\n' "${YELLOW}${CAUSAL_CTX}${NC}"
  printf '\n'
fi

# ── Negative-memory matches for current task ──────────────────────────────────
get_negative_memory_summary() {
  [[ -f "$LEAD_STATE" ]] || { echo ""; return; }
  local task_id
  task_id=$(awk '/^task:/ {print $2; exit}' "$LEAD_STATE")
  [[ -z "$task_id" ]] && { echo ""; return; }

  local nm_matches_file="${PROJECT_ROOT}/docs/handoff/${task_id}/negative-memory-matches.yaml"
  [[ -f "$nm_matches_file" ]] || { echo ""; return; }

  python3 - "$nm_matches_file" <<'PY'
import sys, yaml

with open(sys.argv[1]) as fh:
    data = yaml.safe_load(fh)
if not data or not isinstance(data, dict):
    sys.exit(0)

matches = data.get("matches") or []
if not matches:
    sys.exit(0)

lines = []
for m in matches:
    nm_id   = m.get("nm_id", "?")
    mode    = (m.get("failure_mode") or "")[:60]
    ttl     = m.get("ttl_expires", "")
    disp    = m.get("disposition", "")
    met     = m.get("unblock_criteria_met", 0)
    total   = m.get("unblock_criteria_total", 0)
    unblock = f"unblock criteria met: {met}/{total}" if total else "no unblock criteria"
    status  = "BLOCKED" if disp == "blocked" else ("unblocked" if disp == "unblocked" else disp)
    lines.append(f"  {nm_id} (expires {ttl}) — {mode} [{status}, {unblock}]")

if lines:
    print("\n".join(lines))
PY
}

NM_SUMMARY=$(get_negative_memory_summary)
if [[ -n "$NM_SUMMARY" ]]; then
  printf '%b\n' "${YELLOW}Negative memory:${NC}"
  while IFS= read -r _nm_line; do
    printf -- '%s\n' "$_nm_line"
  done <<< "$NM_SUMMARY"
  printf '\n'
fi

# ── Operator priors summary ──────────────────────────────────────────────────
PRIORS_FILE="${PROJECT_ROOT}/docs/leadv2-priors.yaml"
if [[ -f "$PRIORS_FILE" ]]; then
  python3 - "$PRIORS_FILE" <<'PY'
import sys, yaml, os, time

priors_file = sys.argv[1]
try:
    with open(priors_file) as fh:
        data = yaml.safe_load(fh) or {}
except Exception:
    sys.exit(0)

compiled_at = data.get("compiled_at", "")
age_h = "?"
if compiled_at:
    try:
        import datetime
        ca = datetime.datetime.fromisoformat(compiled_at.replace("Z", "+00:00"))
        age_h = f"{(datetime.datetime.now(datetime.timezone.utc).replace(tzinfo=None) - ca).total_seconds() / 3600:.1f}h"
    except Exception:
        pass

fqp = data.get("fix_quality_priors", {}) or {}
rp  = data.get("risk_priors", {}) or {}
ab  = data.get("active_blocks", {}) or {}

band_aid   = fqp.get("band_aid_ratio_30d", "?")
alert_thr  = fqp.get("alert_threshold", 0.30)
nm_ids     = (ab.get("negative_memory_ids") or [])[:3]
most_regr  = rp.get("most_recent_regression") or "none"

# Band-aid trend color
ba_str = f"{float(band_aid)*100:.0f}%" if isinstance(band_aid, (int, float)) else str(band_aid)
ba_flag = ""
if isinstance(band_aid, (int, float)) and float(band_aid) > float(alert_thr):
    ba_flag = " [ALERT >30%]"

# Next recompile estimate (20h window)
next_recompile = "?"
try:
    mtime = os.path.getmtime(priors_file)
    next_epoch = mtime + 20 * 3600
    now_epoch = time.time()
    diff_h = (next_epoch - now_epoch) / 3600
    if diff_h < 0:
        next_recompile = "overdue"
    else:
        next_recompile = f"in {diff_h:.1f}h"
except Exception:
    pass

print(f"\033[0;36m=== Operator priors (compiled {age_h} ago) ===\033[0m")
print(f"  Band-aid ratio 30d:  {ba_str}{ba_flag}")
print(f"  Most recent regression: {most_regr}")
print(f"  Active NM blocks:    {', '.join(nm_ids) if nm_ids else 'none'}")
print(f"  Next recompile:      {next_recompile}")
print()
PY
fi

# ── Queue lane summary ────────────────────────────────────────────────────────
if [[ -d "$QUEUE_DIR" ]]; then
  printf '%b\n' "${CYAN}=== Queue lanes ===${NC}"
  python3 - "$QUEUE_DIR" <<'PY'
import sys, os, yaml

queue_dir = sys.argv[1]
LANES = ["action", "intelligence", "recovery", "human-needed"]
POISON_COLOR = "\033[0;31m"
RESET = "\033[0m"

for lane in LANES:
    lane_file = os.path.join(queue_dir, f"{lane}.yaml")
    if not os.path.exists(lane_file):
        print(f"  {lane}: (no file)")
        continue
    try:
        items = yaml.safe_load(open(lane_file)) or []
    except Exception:
        print(f"  {lane}: (parse error)")
        continue

    counts: dict[str, int] = {}
    for it in items:
        s = str(it.get("status", "unknown"))
        counts[s] = counts.get(s, 0) + 1

    parts = []
    for status in ["pending", "in-progress", "done", "poisoned", "blocked"]:
        n = counts.get(status, 0)
        if n == 0:
            continue
        if status == "poisoned":
            parts.append(f"{POISON_COLOR}{n} poisoned{RESET}")
        else:
            parts.append(f"{n} {status}")

    summary = " | ".join(parts) if parts else "empty"
    print(f"  {lane}: {summary}")

    # Show poisoned titles for attention
    for it in items:
        if it.get("status") == "poisoned":
            title = str(it.get("title", ""))[:70]
            print(f"    {POISON_COLOR}! {it.get('id','?')}: {title}{RESET}")
PY
  printf '\n'
fi

# Pending decisions summary
if [[ "$PENDING_COUNT" -gt 0 ]]; then
  printf "${YELLOW}=== Pending decisions: %s ===${NC}\n" "$PENDING_COUNT"
  while IFS='|' read -r dec_id dec_question; do
    [[ -z "$dec_id" ]] && continue
    printf -- '  [%s] %s\n' "$dec_id" "$dec_question"
    printf -- '       → answer: bash .claude/scripts/leadv2-decide.sh %s <A|B|C|D>\n' "$dec_id"
  done < <(top_pending 3)
  printf '\n'
fi

# Circuit state indicator
if [[ "$IS_PAUSED" -eq 1 ]]; then
  printf "${RED}DAEMON PAUSED${NC} — %s consecutive failures. Resume: bash .claude/scripts/leadv2-daemon.sh --resume\n\n" "$FAILS"
elif [[ "$HAS_DECISIONS" -eq 1 ]]; then
  printf "${YELLOW}WAITING FOR DECISIONS${NC} — %s pending. Use leadv2-decide.sh to answer.\n\n" "$PENDING_COUNT"
else
  printf '%b\n\n' "${GREEN}OK${NC} — daemon running normally."
fi

exit "$EXIT_CODE"
