#!/bin/bash
# install-tmux-statusline.sh — opt-in tmux statusline installer for leadv2.
#
# CODEX-TMUX-STATUSLINE-01. Fully opt-in: the main codex-lead install.sh
# never mutates a tmux config, and this script never edits one either unless
# --tmux-conf PATH names the file explicitly.
#
#   default            installs/prepares assets only (generated conf under
#                      $XDG_CONFIG_HOME/leadv2/) and prints the activation
#                      command; touches no tmux config
#   --tmux-conf PATH   additionally adds a sentinel-delimited managed
#                      `source-file` block to PATH, idempotently, preserving
#                      all non-managed content (backup .bak on change)
#
# Activation is by tmux source-file inclusion — no shell prompt hacks. The
# generated conf sets status-interval/status-right*, so it REPLACES any
# existing status-right for the server that sources it; uninstall restores
# nothing automatically (see docs/codex-tmux-statusline.md).
#
# Test seams: redirect $HOME (fixture) and/or pass --tmux-conf <fixture path>.
#
# Usage:
#   install-tmux-statusline.sh [--tmux-conf PATH]
#
# Exit codes:
#   0   ran to completion
#   2   bad arguments
#   4   cannot write the generated conf, or --tmux-conf target unwritable
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WRAPPER="$SCRIPT_DIR/leadv2-tmux-status.sh"
CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/leadv2"
CONF_OUT="$CONF_DIR/tmux-statusline.conf"

SENTINEL_BEGIN="# BEGIN leadv2 tmux statusline (managed by plugins/leadv2/codex-lead/statusline/install-tmux-statusline.sh)"
SENTINEL_END="# END leadv2 tmux statusline"

usage() {
  printf 'usage: install-tmux-statusline.sh [--tmux-conf PATH]\n' >&2
}

TMUX_CONF=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --tmux-conf)
      [[ $# -ge 2 ]] || { usage; exit 2; }
      TMUX_CONF="$2"; shift 2 ;;
    --tmux-conf=*)
      TMUX_CONF="${1#--tmux-conf=}"; shift ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      printf 'install-tmux-statusline.sh: unknown argument: %s\n' "$1" >&2
      usage; exit 2 ;;
  esac
done

if [[ ! -f "$WRAPPER" ]]; then
  printf 'install-tmux-statusline.sh: wrapper missing: %s\n' "$WRAPPER" >&2
  exit 4
fi
chmod +x "$WRAPPER" 2>/dev/null || :

# --- 1. generate the activation conf (the only asset) ----------------------
# The #() payload is double-quoted inside the single-quoted tmux format
# string: tmux hands the #() content to popen → sh, so the double quotes make
# a wrapper path with spaces one safe word. No eval anywhere.
CONF_BODY="# leadv2 tmux statusline — generated by install-tmux-statusline.sh; edit is futile (regenerated on install)
set -g status-interval 15
set -g status-right-length 100
set -g status-right '#(\"$WRAPPER\")'"

if ! mkdir -p "$CONF_DIR" 2>/dev/null; then
  printf 'install-tmux-statusline.sh: cannot create %s\n' "$CONF_DIR" >&2
  exit 4
fi
CHANGED_CONF=0
if [[ ! -f "$CONF_OUT" ]] || ! printf '%s\n' "$CONF_BODY" | diff -q - "$CONF_OUT" >/dev/null 2>&1; then
  [[ -f "$CONF_OUT" ]] && cp "$CONF_OUT" "$CONF_OUT.bak"
  if ! printf '%s\n' "$CONF_BODY" > "$CONF_OUT" 2>/dev/null; then
    printf 'install-tmux-statusline.sh: cannot write %s\n' "$CONF_OUT" >&2
    exit 4
  fi
  CHANGED_CONF=1
fi

if [[ "$CHANGED_CONF" == "1" ]]; then
  printf 'conf: generated %s\n' "$CONF_OUT"
else
  printf 'conf: unchanged %s\n' "$CONF_OUT"
fi

# --- 2. managed block in the tmux config (explicit --tmux-conf only) -------
if [[ -n "$TMUX_CONF" ]]; then
  BLOCK="$SENTINEL_BEGIN
source-file '$CONF_OUT'
$SENTINEL_END"

  if [[ -d "$TMUX_CONF" ]]; then
    printf 'install-tmux-statusline.sh: --tmux-conf is a directory: %s\n' "$TMUX_CONF" >&2
    exit 4
  fi
  if [[ -f "$TMUX_CONF" ]] && [[ ! -w "$TMUX_CONF" ]]; then
    printf 'install-tmux-statusline.sh: %s is not writable\n' "$TMUX_CONF" >&2
    exit 4
  fi

  # strip any existing managed block (and its separator blank line), then
  # append the current one — keeps non-managed content byte-identical and the
  # block single across repeated runs. Mirrors uninstall's strip exactly.
  TMP_CONF="$(mktemp "${TMPDIR:-/tmp}/leadv2-tmux-conf.XXXXXX")" || exit 4
  if [[ -f "$TMUX_CONF" ]]; then
    python3 - "$TMUX_CONF" "$TMP_CONF" "$SENTINEL_BEGIN" "$SENTINEL_END" <<'PYEOF' || { rm -f "$TMP_CONF"; exit 4; }
import sys
src, dst, begin, end = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
with open(src) as f:
    lines = f.readlines()
out = []
inblk = False
for line in lines:
    if line.rstrip('\n') == begin:
        inblk = True
        if out and out[-1].strip() == '':
            out.pop()  # the separator blank line this installer added
        continue
    if inblk:
        if line.rstrip('\n') == end:
            inblk = False
        continue
    out.append(line)
if inblk:
    sys.exit(1)  # unbalanced block: refuse rather than build on half a block
with open(dst, 'w') as f:
    f.writelines(out)
PYEOF
  fi
  # ensure the file ends with a newline before appending
  if [[ -s "$TMP_CONF" ]] && [[ "$(tail -c 1 "$TMP_CONF" | od -An -c | tr -d ' ')" != '\n' ]]; then
    printf '\n' >> "$TMP_CONF"
  fi
  printf '\n%s\n' "$BLOCK" >> "$TMP_CONF"

  if [[ -f "$TMUX_CONF" ]]; then
    if diff -q "$TMP_CONF" "$TMUX_CONF" >/dev/null 2>&1; then
      printf 'tmux.conf: managed block unchanged %s\n' "$TMUX_CONF"
      rm -f "$TMP_CONF"
    else
      cp "$TMUX_CONF" "$TMUX_CONF.bak"
      if ! mv "$TMP_CONF" "$TMUX_CONF"; then
        printf 'install-tmux-statusline.sh: cannot update %s\n' "$TMUX_CONF" >&2
        rm -f "$TMP_CONF"
        exit 4
      fi
      printf 'tmux.conf: managed block added/updated %s (backup: %s.bak)\n' "$TMUX_CONF" "$TMUX_CONF"
    fi
  else
    if ! mv "$TMP_CONF" "$TMUX_CONF"; then
      printf 'install-tmux-statusline.sh: cannot create %s\n' "$TMUX_CONF" >&2
      rm -f "$TMP_CONF"
      exit 4
    fi
    printf 'tmux.conf: created with managed block %s\n' "$TMUX_CONF"
  fi
fi

# --- 3. activation instructions --------------------------------------------
printf '\n'
if [[ -z "$TMUX_CONF" ]]; then
  printf 'No tmux config was touched (fully opt-in). To activate:\n'
else
  printf 'To activate for the running server (no restart needed):\n'
fi
printf '  tmux source-file %s\n' "$CONF_OUT"
if [[ -z "$TMUX_CONF" ]]; then
  printf 'To make it persistent across servers, re-run with an explicit config:\n'
  printf '  %s --tmux-conf ~/.tmux.conf\n' "$0"
fi
exit 0
