#!/bin/bash
# leadv2-tmux-status.sh — tmux bottom-status-bar surface for leadv2 status.
#
# Called by tmux via #(...) from the conf generated by
# install-tmux-statusline.sh. Wraps codex-lead/leadv2-codex-status.sh with a
# 15-30s file cache so the tmux status bar never blocks on the underlying
# quota/lane probes: a fresh cache is a plain cat, a stale cache is refreshed
# once under a timeout (if `timeout` exists), and any failure degrades to the
# last good line or a compact "leadv2 ?" fallback — never an empty bar, never
# a non-zero exit (a non-zero exit would render nothing until the next
# status-interval tick).
#
# Test seams (both optional):
#   LEADV2_STATUSLINE_CMD    — overrides the wrapped status command
#   LEADV2_STATUSLINE_CACHE  — overrides the cache file path
#   LEADV2_STATUSLINE_TTL    — cache TTL seconds (default 20, contract 15-30)
#
# Usage: leadv2-tmux-status.sh   (no arguments)
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATUS_CMD="${LEADV2_STATUSLINE_CMD:-$SCRIPT_DIR/../leadv2-codex-status.sh}"
TTL="${LEADV2_STATUSLINE_TTL:-20}"
if ! [[ "$TTL" =~ ^[0-9]+$ ]]; then
  TTL=20
fi
CACHE="${LEADV2_STATUSLINE_CACHE:-${XDG_CACHE_HOME:-${HOME:-/tmp}/.cache}/leadv2/tmux-statusline/status.cache}"
FALLBACK="leadv2 ?"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  printf 'usage: leadv2-tmux-status.sh\n' >&2
  exit 0
fi

# macOS has no `timeout` by default — same convention as
# leadv2-codex-status.sh: bound the refresh only when the tool exists.
TIMEOUT_BIN=""
command -v timeout >/dev/null 2>&1 && TIMEOUT_BIN="timeout 8"

now="$(date +%s)"
age() { # age of $CACHE in seconds; huge when missing
  local mtime
  mtime="$(stat -f %m "$CACHE" 2>/dev/null || stat -c %Y "$CACHE" 2>/dev/null)"
  if [[ "$mtime" =~ ^[0-9]+$ ]]; then
    printf '%s\n' "$((now - mtime))"
  else
    printf '999999\n'
  fi
}

first_line() { # collapse to one bar-safe line, capped at 100 chars
  printf '%s' "$1" | head -n 1 | cut -c 1-100
}

cache_write() { # atomic (tmp + mv) so a concurrent tmux tick never reads a partial line
  local cache_dir
  cache_dir="$(dirname "$CACHE")"
  mkdir -p "$cache_dir" 2>/dev/null || return 1
  local tmp
  tmp="$(mktemp "$cache_dir/.status.XXXXXX" 2>/dev/null)" || return 1
  printf '%s\n' "$1" > "$tmp" 2>/dev/null || { rm -f "$tmp"; return 1; }
  mv -f "$tmp" "$CACHE" 2>/dev/null || { rm -f "$tmp"; return 1; }
  return 0
}

if [[ -f "$CACHE" ]] && [[ "$(age)" -lt "$TTL" ]]; then
  # cache hit: no subprocess beyond date/stat — the fast path
  CACHED="$(head -n 1 "$CACHE" 2>/dev/null)"
  if [[ -n "$CACHED" ]]; then
    printf '%s\n' "$CACHED"
    exit 0
  fi
fi

# stale or missing: refresh once, bounded
OUT=""
if [[ -x "$STATUS_CMD" || -r "$STATUS_CMD" ]]; then
  OUT="$($TIMEOUT_BIN bash "$STATUS_CMD" 2>/dev/null)"
fi
if [[ -n "$OUT" ]]; then
  LINE="$(first_line "$OUT")"
  cache_write "$LINE" || :
  printf '%s\n' "$LINE"
  exit 0
fi

# refresh failed: stale-while-error — keep the last good line if any
if [[ -f "$CACHE" ]]; then
  CACHED="$(head -n 1 "$CACHE" 2>/dev/null)"
  if [[ -n "$CACHED" ]]; then
    printf '%s\n' "$CACHED"
    exit 0
  fi
fi

printf '%s\n' "$FALLBACK"
exit 0
